### ISSUE TITLE
Introduce node js with bundler and transpiler

### ISSUE THREAD

**Issue by tim-kilian** [creativecommons/cc-license-chooser#7]
**feature request**
I would like to have a library that I can install via common package manager like npm or yarn. That could generate and bundle the resulting js with a wide range browser compatibility.

**Describe the solution you'd like**
First step to get rid of the php and the python bundlers could be to introduce node with webpack and babel for example.

**Describe alternatives you've considered**
I would also suggest to build a vue component and create a widget with the [vue-custom-element](https://github.com/karol-f/vue-custom-element) package.

**Comment by adityaas26** [comment]
I won't suggest using external libraries to add features in the widget as it will make the widget heavier. We must focus on keeping the footprints minimal in the network.

I support the idea of using [vue-custom-element](https://karol-f.github.io/vue-custom-element/#/) for developing the package.
